#!/usr/bin/env python3
"""
Drone Mission Plotter and Hijack Detection System

This script provides real-time monitoring and visualization for drone missions,
with integrated hijack detection based on path deviation and telemetry loss.

Key Features:
- Real-time position tracking from log files
- Path deviation detection with configurable thresholds
- Telemetry loss detection and tracking
- Visual display with drone trajectories and status indicators
- CSV logging of hijack events for post-analysis
- Multi-drone support for swarm operations

Detection Criteria:
- Path deviation > 0.3 meters from planned trajectory
- Telemetry loss > 3 seconds
- Manual hijack detection flag

The plotter reads position logs generated by the victim mission script and
updates the display in real-time, coloring drone markers based on their
current status (normal, off-course, telemetry loss, or hijacked).
"""

import matplotlib.pyplot as plt
import numpy as np
import json
import time
import os
import glob
from datetime import datetime
from collections import deque
import matplotlib.gridspec as gridspec
from matplotlib.patches import Rectangle
import csv


class DroneMissionPlotter:
    """
    Real-time drone mission monitor with hijack detection.
    
    Monitors drone positions from log files, detects anomalies,
    and provides visual feedback with historical message logs.
    """
    
    def __init__(self, missions, experiment_name="hijack_experiment"):
        """
        Initialize the plotter with mission definitions.
        
        Args:
            missions: Dictionary mapping drone URIs to (start_point, waypoints)
            experiment_name: Name for this experiment run
        """
        self.missions = missions
        self.experiment_name = experiment_name
        self.experiment_start_time = time.time()
        self.drone_progress = {}
        self.consecutive_missing_count = {}
        
        # Hijack metrics for research paper
        self.hijack_metrics = {}
        self.hijack_results = {}
        
        # Track hijack events
        self.hijack_events = []
        self.hijack_report_counter = 0
        self.takeoff_end_time = {}
    
        # Initialize hijack events CSV
        self.init_hijack_events_csv()

        # Initialize all data structures
        self.drone_files = {}
        self.drone_positions = {}
        self.drone_paths = {}
        self.drone_colors = {}
        self.controller_history = {}
        self.anomaly_status = {}
        self.anomaly_start_time = {}
        
        # Message history for side panel
        self.message_history = deque(maxlen=100)
        self.message_display_count = 15
        self.current_page = 0
        
        # Data rate monitoring
        self.last_data_timestamps = {}
        self.last_actual_data_timestamps = {}
        self.data_rate_anomalies = {}
        self.no_data_alerts_sent = {}
        
        # Hijack tracking for both drones
        self.hijack_detected = {uri: False for uri in missions.keys()}
        self.hijack_start_time = {uri: None for uri in missions.keys()}
        self.hijack_end_time = {uri: None for uri in missions.keys()}
        self.time_to_first_anomaly = {uri: None for uri in missions.keys()}
        self.max_path_deviation = {uri: 0 for uri in missions.keys()}
        self.total_telemetry_loss = {uri: 0 for uri in missions.keys()}
        self.total_hijack_duration = {uri: 0 for uri in missions.keys()}
        
        # Track current state
        self.current_data_anomaly_start = {uri: None for uri in missions.keys()}
        self.current_path_anomaly_start = {uri: None for uri in missions.keys()}
        
        # Results file
        self.results_file = f"hijack_results_{datetime.now().strftime('%Y%m%d_%H%M%S')}.csv"
        
        # Setup the plot with side panel
        self.setup_plot_with_messages()
        
        # Initialize results file
        self.init_results_file()
        
        # Remove all previous log files for fresh start
        self.cleanup_previous_logs()
        
        self.setup_mission_layout()
    
    def get_mission_progress(self, uri):
        """
        Get current mission progress for a drone.
        
        Args:
            uri: Drone URI
        
        Returns:
            Dictionary with progress information
        """
        if not hasattr(self, 'drone_progress') or uri not in self.drone_progress:
            return {
                'current_index': 0,
                'total_targets': 0,
                'current_waypoint': [0, 0],
                'next_waypoint': [0, 0],
                'expected_path': [],
                'progress': 0
            }
    
        progress = self.drone_progress[uri]
        expected_path = self.drone_paths.get(uri, [])
    
        current_idx = progress.get('current_target_index', 0)
        total_targets = len(expected_path)
    
        # Get current and next waypoints
        current_waypoint = [0, 0]
        next_waypoint = [0, 0]
    
        if current_idx < len(expected_path):
            current_waypoint = [expected_path[current_idx][0], expected_path[current_idx][1]]
        if current_idx + 1 < len(expected_path):
            next_waypoint = [expected_path[current_idx + 1][0], expected_path[current_idx + 1][1]]
    
        # Calculate progress (0 to 1)
        progress_value = current_idx / total_targets if total_targets > 0 else 0
    
        # Build expected path points (just x,y)
        path_points = [[p[0], p[1]] for p in expected_path]
    
        return {
            'current_index': current_idx,
            'total_targets': total_targets,
            'current_waypoint': current_waypoint,
            'next_waypoint': next_waypoint,
            'expected_path': path_points,
            'progress': progress_value
        }

    def get_last_line_count(self, uri):
        """
        Get last read line count from log file.
        
        Args:
            uri: Drone URI
        
        Returns:
            Number of lines in log file
        """
        filename = self.drone_files.get(uri)
        if not filename or not os.path.exists(filename):
            return 0
    
        try:
            with open(filename, 'r') as f:
                lines = f.readlines()
                return len(lines)
        except:
            return 0

    def generate_alerts_for_drone(self, uri, pos_data, drone_num, current_time):
        """
        Generate alerts based on current drone state.
        
        Args:
            uri: Drone URI
            pos_data: Current position data
            drone_num: Drone number for display
            current_time: Current timestamp
        
        Returns:
            List of alert dictionaries
        """
        alerts = []
        
        # Skip alerts for dormant (landed) drones
        if self.is_drone_landed(uri, pos_data):
            return alerts
    
        # Data rate anomaly alert
        if pos_data.get('data_rate_anomaly', False):
            anomaly_level = pos_data.get('anomaly_level', 'ALARM')
            data_age = pos_data.get('data_age', 0)
        
            alert = {
                "id": f"{uri.split('/')[-1]}_data_{int(current_time * 1000)}",
                "alert_type": "DATA_RATE",
                "python_timestamp": current_time,
                "raw_message": f"{anomaly_level}: Drone {drone_num} - no data for {data_age:.1f}s",
                "drone_uri": uri,
                "drone_index": drone_num,
                "trigger_value": data_age,
                "threshold": 3.0,
                "is_state_change": not self.anomaly_status.get(uri, False),
                "is_recovery": False,
                "source_module": "check_data_rate_anomaly",
                "anomaly_level": anomaly_level
            }
        
            # Check if this is a state change (just started)
            if not self.anomaly_status.get(uri, False):
                alert['state_before'] = "NORMAL"
                alert['state_after'] = anomaly_level
        
            alerts.append(alert)
    
        # Path deviation alert
        if pos_data.get('is_off_course', False):
            distance = pos_data.get('distance_from_path', 0)
        
            alert = {
                "id": f"{uri.split('/')[-1]}_path_{int(current_time * 1000)}",
                "alert_type": "ANOMALY",
                "python_timestamp": current_time,
                "raw_message": f"PATH DEVIATION: Drone {drone_num} is {distance:.2f}m from expected path",
                "drone_uri": uri,
                "drone_index": drone_num,
                "trigger_value": distance,
                "threshold": 0.3,
                "is_state_change": not self.anomaly_status.get(uri, False),
                "is_recovery": False,
                "source_module": "check_if_off_course",
                "anomaly_level": "ALARM"
            }
        
            # Add kinematic data if available
            if 'current_speed' in pos_data:
                alert['kinematic_data'] = {
                    "speed": pos_data.get('current_speed', 0),
                    "expected_speed": 1.0,
                    "acceleration": 0
                }
        
            alerts.append(alert)
    
        # Recovery alert (if anomalies cleared)
        if not pos_data.get('data_rate_anomaly', False) and not pos_data.get('is_off_course', False):
            if self.anomaly_status.get(uri, False):
                alert = {
                    "id": f"{uri.split('/')[-1]}_recovery_{int(current_time * 1000)}",
                    "alert_type": "RECOVERY",
                    "python_timestamp": current_time,
                    "raw_message": f"Drone {drone_num} recovered to normal operation",
                    "drone_uri": uri,
                    "drone_index": drone_num,
                    "is_recovery": True,
                    "source_module": "system"
                }
                alerts.append(alert)
    
        return alerts
    
    def get_consecutive_missing(self, uri):
        """
        Get number of consecutive missing data packets.
        
        Args:
            uri: Drone URI
        
        Returns:
            Count of consecutive missing packets
        """
        # Track consecutive missing packets per drone
        if not hasattr(self, 'consecutive_missing_count'):
            self.consecutive_missing_count = {}
    
        if uri not in self.consecutive_missing_count:
            self.consecutive_missing_count[uri] = 0
    
        # If currently in data anomaly, increment counter logic
        if self.data_rate_anomalies.get(uri, False):
            return min(self.consecutive_missing_count[uri] + 1, 10)
        else:
            self.consecutive_missing_count[uri] = 0
            return 0
    
    def calculate_swarm_metrics(self, drones):
        """
        Calculate swarm-level metrics.
        
        Args:
            drones: List of drone state dictionaries
        
        Returns:
            Dictionary of swarm metrics
        """
        total_drones = len(drones)
        active_drones = sum(1 for d in drones if d['status'] == 'active')
        anomalous_drones = sum(1 for d in drones if d['status'] == 'anomalous')
    
        path_anomalies = 0
        data_anomalies = 0
        critical_anomalies = 0
    
        for d in drones:
            if d['anomalies']['path_deviation']['detected']:
                path_anomalies += 1
            if d['anomalies']['data_rate']['detected']:
                data_anomalies += 1
                if d['anomalies']['data_rate']['level'] in ['ALARM', 'CRITICAL']:
                    critical_anomalies += 1
    
        recovering_drones = 0
    
        return {
            "swarm": {
                "total_drones": total_drones,
                "active_drones": active_drones,
                "connected_drones": active_drones,
                "anomalous_drones": anomalous_drones
            },
            "anomalies": {
                "total_anomalies": path_anomalies + data_anomalies,
                "path_anomalies": path_anomalies,
                "data_anomalies": data_anomalies,
                "critical_anomalies": critical_anomalies,
                "recovering_drones": recovering_drones
            }
        }
                    
    def generate_hijack_report(self, uri, anomaly_type, current_time, distance_to_path=None, data_age=None):
        """
        Generate a mini-report for a single hijack event.
        
        Args:
            uri: Drone URI
            anomaly_type: Type of anomaly detected
            current_time: Current timestamp
            distance_to_path: Distance from expected path (optional)
            data_age: Age of last data packet (optional)
        
        Returns:
            Path to generated report file
        """
        drone_num = list(self.missions.keys()).index(uri) + 1
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        report_file = f"hijack_event_{drone_num}_{timestamp}_{self.hijack_report_counter}.txt"
        self.hijack_report_counter += 1
        
        # Calculate event metrics
        event_metrics = {
            'drone_id': drone_num,
            'uri': uri,
            'timestamp': timestamp,
            'anomaly_type': anomaly_type,
            'experiment_time': current_time - self.experiment_start_time,
            'distance_to_path': distance_to_path or 0,
            'data_age': data_age or 0,
            'max_deviation_so_far': self.max_path_deviation.get(uri, 0),
            'telemetry_loss_so_far': self.total_telemetry_loss.get(uri, 0),
            'hijack_duration_so_far': self.total_hijack_duration.get(uri, 0)
        }
        
        # Add to events list
        self.hijack_events.append(event_metrics)
        
        # Generate report
        with open(report_file, 'w') as f:
            f.write("="*60 + "\n")
            f.write(f"HIJACK EVENT DETECTED - DRONE {drone_num}\n")
            f.write("="*60 + "\n\n")
            
            f.write(f"Event Time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
            f.write(f"Experiment Time: {event_metrics['experiment_time']:.1f} seconds\n")
            f.write(f"Anomaly Type: {anomaly_type}\n")
            f.write(f"Drone URI: {uri}\n\n")
            
            f.write("DETECTION DETAILS:\n")
            f.write("-"*60 + "\n")
            if distance_to_path:
                f.write(f"Path Deviation: {distance_to_path:.2f}m")
                if distance_to_path > 1.0:
                    f.write(" (>1.0m SUCCESS)\n")
                else:
                    f.write("\n")
            if data_age:
                f.write(f"Telemetry Age: {data_age:.1f}s")
                if data_age > 3.0:
                    f.write(" (>3s SUCCESS)\n")
                else:
                    f.write("\n")
            
            f.write("\nCUMULATIVE METRICS:\n")
            f.write("-"*60 + "\n")
            f.write(f"Max Path Deviation: {self.max_path_deviation.get(uri, 0):.2f}m\n")
            f.write(f"Total Telemetry Loss: {self.total_telemetry_loss.get(uri, 0):.1f}s\n")
            f.write(f"Total Hijack Duration: {self.total_hijack_duration.get(uri, 0):.1f}s\n")
            f.write(f"Time to First Anomaly: {self.time_to_first_anomaly.get(uri, 0):.1f}s\n")
            
            f.write("\nSUCCESS CRITERIA STATUS:\n")
            f.write("-"*60 + "\n")
            success_criteria = []
            if self.max_path_deviation.get(uri, 0) > 1.0:
                success_criteria.append("Path Deviation >1.0m")
            if self.total_telemetry_loss.get(uri, 0) > 3.0:
                success_criteria.append("Telemetry Loss >3.0s")
            if self.hijack_detected.get(uri, False):
                success_criteria.append("Manual Hijack Detection")
            
            if success_criteria:
                for criterion in success_criteria:
                    f.write(f" - {criterion}\n")
                f.write(f"\nHIJACK SUCCESSFUL - {len(success_criteria)} criteria met\n")
            else:
                f.write("No success criteria met yet\n")
            
            f.write("\n" + "="*60 + "\n")
        
        # Print to console
        print(f"\n[HIJACK EVENT] Drone {drone_num} - {anomaly_type}")
        print(f"  Report saved to: {report_file}")
        if success_criteria:
            print(f"  HIJACK SUCCESSFUL")
        
        # Add to message panel
        self.add_message(f"HIJACK EVENT: Drone {drone_num} - {anomaly_type} - report saved", "SUCCESS")
        
        return report_file
    
    def init_results_file(self):
        """Initialize CSV file for recording hijack results."""
        with open(self.results_file, 'w', newline='') as f:
            writer = csv.writer(f)
            writer.writerow([
                'timestamp', 'drone_id', 'x', 'y', 'z', 'controller',
                'distance_to_path', 'data_age_seconds', 'hijack_detected',
                'anomaly_type', 'max_path_deviation', 'telemetry_loss_duration',
                'time_to_first_anomaly', 'hijack_duration'
            ])
        self.add_message(f"Results file created: {self.results_file}", "SYSTEM")

    def init_hijack_events_csv(self):
        """Initialize CSV file for hijack events."""
        self.hijack_events_file = f"hijack_events_{datetime.now().strftime('%Y%m%d_%H%M%S')}.csv"
        with open(self.hijack_events_file, 'w', newline='') as f:
            writer = csv.writer(f)
            writer.writerow([
                'event_id', 'drone_id', 'timestamp', 'anomaly_type', 
                'experiment_time', 'distance_to_path', 'data_age',
                'max_deviation', 'telemetry_loss', 'hijack_duration',
                'success_criteria_met', 'event_type'
            ])
        self.hijack_event_counter = 0

    def record_hijack_event(self, uri, anomaly_type, current_time, event_type="DETECTION", 
                           distance_to_path=None, data_age=None):
        """
        Record hijack event to CSV.
        
        Args:
            uri: Drone URI
            anomaly_type: Type of anomaly
            current_time: Current timestamp
            event_type: Type of event (DETECTION, START, END)
            distance_to_path: Distance from path (optional)
            data_age: Age of data (optional)
        """
        drone_num = list(self.missions.keys()).index(uri) + 1
        timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        
        # Calculate success criteria
        success_criteria = 0
        if distance_to_path and distance_to_path > 1.0:
            success_criteria += 1
        if data_age and data_age > 3.0:
            success_criteria += 1
        if anomaly_type == "HIJACK_DETECTED":
            success_criteria += 1
        
        with open(self.hijack_events_file, 'a', newline='') as f:
            writer = csv.writer(f)
            writer.writerow([
                self.hijack_event_counter, drone_num, timestamp, anomaly_type,
                current_time - self.experiment_start_time, distance_to_path or 0,
                data_age or 0, self.max_path_deviation.get(uri, 0),
                self.total_telemetry_loss.get(uri, 0), 
                self.total_hijack_duration.get(uri, 0),
                success_criteria, event_type
            ])
        
        self.hijack_event_counter += 1

    def record_hijack_result(self, uri, pos_data, distance_to_path, data_age, anomaly_detected, anomaly_type):
        """
        Record detailed results for research paper.
        
        Args:
            uri: Drone URI
            pos_data: Position data dictionary
            distance_to_path: Distance from planned path
            data_age: Age of data
            anomaly_detected: Whether anomaly was detected
            anomaly_type: Type of anomaly
        """
        drone_num = list(self.missions.keys()).index(uri) + 1
        timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S.%f')[:-3]
        
        # Calculate metrics for this drone
        hijack_duration = 0
        if self.hijack_start_time[uri] is not None:
            if self.hijack_end_time[uri] is not None:
                hijack_duration = self.hijack_end_time[uri] - self.hijack_start_time[uri]
            else:
                hijack_duration = time.time() - self.hijack_start_time[uri]
        
        # Write to CSV
        with open(self.results_file, 'a', newline='') as f:
            writer = csv.writer(f)
            writer.writerow([
                timestamp, drone_num, pos_data.get('x', 0), pos_data.get('y', 0), 
                pos_data.get('z', 0), pos_data.get('controller', 'unknown'),
                distance_to_path, data_age, int(anomaly_detected),
                anomaly_type, self.max_path_deviation[uri],
                self.total_telemetry_loss[uri],
                self.time_to_first_anomaly[uri] if self.time_to_first_anomaly[uri] else 0,
                hijack_duration
            ])
            
    def update_hijack_metrics(self, uri, anomaly_type, current_time, distance_to_path=None, data_age=None):
        """
        Update hijack metrics based on detected anomaly.
        
        Args:
            uri: Drone URI
            anomaly_type: Type of anomaly
            current_time: Current timestamp
            distance_to_path: Distance from path (optional)
            data_age: Age of data (optional)
        """
        drone_num = list(self.missions.keys()).index(uri) + 1
    
        # Initialize if not exists
        if uri not in self.total_hijack_duration:
            self.total_hijack_duration[uri] = 0
    
        # Track max path deviation
        if distance_to_path and distance_to_path > self.max_path_deviation.get(uri, 0):
            self.max_path_deviation[uri] = distance_to_path
    
        # Track telemetry loss
        if data_age and data_age > 3.0:
            if self.current_data_anomaly_start.get(uri) is None:
                self.current_data_anomaly_start[uri] = current_time - data_age
            self.total_telemetry_loss[uri] = current_time - self.current_data_anomaly_start[uri]
    
        # Track time to first anomaly
        if self.time_to_first_anomaly.get(uri) is None and anomaly_type != "NONE":
            self.time_to_first_anomaly[uri] = current_time - self.experiment_start_time
    
        # Record event to CSV
        self.record_hijack_event(uri, anomaly_type, current_time, "DETECTION", 
                               distance_to_path, data_age)
    
        # Check for hijack state changes
        if anomaly_type in ["PATH_DEVIATION", "TELEMETRY_LOSS", "HIJACK_DETECTED"]:
            if not self.hijack_detected.get(uri, False):
                # New hijack detected
                self.hijack_detected[uri] = True
                self.hijack_start_time[uri] = current_time
            
                # Generate detailed report
                report_file = self.generate_hijack_report(uri, anomaly_type, current_time, 
                                                         distance_to_path, data_age)
            
                # Record start event
                self.record_hijack_event(uri, anomaly_type, current_time, "START", 
                                       distance_to_path, data_age)
            
                print(f"\n[HIJACK START] Drone {drone_num}")
                print(f"  Type: {anomaly_type}")
                if distance_to_path:
                    print(f"  Deviation: {distance_to_path:.2f}m")
                if data_age:
                    print(f"  Data age: {data_age:.1f}s")
                print(f"  Report: {report_file}")
        
            else:
                # Continuing hijack - accumulate time
                if self.hijack_start_time.get(uri):
                    elapsed = current_time - self.hijack_start_time[uri]
                    self.hijack_start_time[uri] = current_time
                    self.total_hijack_duration[uri] += elapsed
    
        elif anomaly_type == "NONE" and self.hijack_detected.get(uri, False):
            # Hijack ended
            if self.hijack_start_time.get(uri):
                final_elapsed = current_time - self.hijack_start_time[uri]
                self.total_hijack_duration[uri] += final_elapsed
        
            # Record end event
            self.record_hijack_event(uri, "NONE", current_time, "END", 
                                   distance_to_path, data_age)
        
            self.hijack_detected[uri] = False
            self.hijack_start_time[uri] = None
        
            print(f"\n[HIJACK END] Drone {drone_num}")
            print(f"  Total duration: {self.total_hijack_duration.get(uri, 0):.1f}s")
            print(f"  Max deviation: {self.max_path_deviation.get(uri, 0):.2f}m")
            print(f"  Telemetry loss: {self.total_telemetry_loss.get(uri, 0):.1f}s")
    
    def generate_experiment_summary(self):
        """Generate final experiment summary for research paper."""
        try:
            summary_file = self.results_file.replace('.csv', '_summary.txt')
        
            with open(summary_file, 'w') as f:
                f.write("="*80 + "\n")
                f.write("DRONE HIJACKING EXPERIMENT RESULTS\n")
                f.write("="*80 + "\n\n")
            
                f.write(f"Experiment: {self.experiment_name}\n")
                f.write(f"Start Time: {datetime.fromtimestamp(self.experiment_start_time)}\n")
                f.write(f"End Time: {datetime.now()}\n")
                f.write(f"Duration: {time.time() - self.experiment_start_time:.1f} seconds\n\n")
            
                f.write("SUCCESS CRITERIA:\n")
                f.write("  1. Telemetry loss > 3 seconds (communication hijacked)\n")
                f.write("  2. Path deviation > 1.0 meters (control hijacked)\n")
                f.write("  3. Manual hijack detection flag\n\n")
            
                f.write("SWARM HIJACKING PERFORMANCE METRICS\n")
                f.write("="*80 + "\n")
                f.write("Metric               Drone 1      Drone 2      Average\n")
                f.write("-"*80 + "\n")
            
                # Get drone URIs in order
                drone_uris = list(self.missions.keys())
                drone1_uri = drone_uris[0] if len(drone_uris) > 0 else None
                drone2_uri = drone_uris[1] if len(drone_uris) > 1 else None
            
                # Calculate success rates
                success_count = 0
                for uri in self.missions.keys():
                    # Check if any success criterion was met
                    success = (self.max_path_deviation.get(uri, 0) > 1.0 or 
                              self.total_telemetry_loss.get(uri, 0) > 3.0 or
                              self.hijack_detected.get(uri, False))
                    if success:
                        success_count += 1
            
                success_rate = (success_count / len(self.missions)) * 100 if self.missions else 0
            
                # Time to first anomaly
                time_to_first = []
                for uri in self.missions.keys():
                    if self.time_to_first_anomaly.get(uri):
                        time_to_first.append(self.time_to_first_anomaly[uri])
            
                avg_time_to_first = np.mean(time_to_first) if time_to_first else 0
            
                # Max path deviation
                max_deviations = [self.max_path_deviation.get(uri, 0) for uri in self.missions.keys()]
                avg_max_deviation = np.mean(max_deviations) if max_deviations else 0
            
                # Telemetry loss duration
                telemetry_losses = [self.total_telemetry_loss.get(uri, 0) for uri in self.missions.keys()]
                avg_telemetry_loss = np.mean(telemetry_losses) if telemetry_losses else 0
            
                # Total hijack duration
                hijack_durations = []
                for uri in self.missions.keys():
                    total_duration = self.total_hijack_duration.get(uri, 0)
                    # Add any ongoing hijack time
                    if self.hijack_detected.get(uri, False) and self.hijack_start_time.get(uri):
                        ongoing = time.time() - self.hijack_start_time[uri]
                        total_duration += ongoing
                    hijack_durations.append(total_duration)
            
                avg_hijack_duration = np.mean(hijack_durations) if hijack_durations else 0
            
                # Get individual drone values - ensure they are floats (not None)
                drone1_time = self.time_to_first_anomaly.get(drone1_uri, 0) if drone1_uri else 0
                drone2_time = self.time_to_first_anomaly.get(drone2_uri, 0) if drone2_uri else 0
            
                drone1_dev = self.max_path_deviation.get(drone1_uri, 0) if drone1_uri else 0
                drone2_dev = self.max_path_deviation.get(drone2_uri, 0) if drone2_uri else 0
            
                drone1_loss = self.total_telemetry_loss.get(drone1_uri, 0) if drone1_uri else 0
                drone2_loss = self.total_telemetry_loss.get(drone2_uri, 0) if drone2_uri else 0
            
                # Get hijack durations with ongoing time included
                drone1_hijack = self.total_hijack_duration.get(drone1_uri, 0) if drone1_uri else 0
                drone2_hijack = self.total_hijack_duration.get(drone2_uri, 0) if drone2_uri else 0
            
                # Convert None to 0.0 for formatting
                drone1_time = float(drone1_time) if drone1_time is not None else 0.0
                drone2_time = float(drone2_time) if drone2_time is not None else 0.0
                drone1_dev = float(drone1_dev) if drone1_dev is not None else 0.0
                drone2_dev = float(drone2_dev) if drone2_dev is not None else 0.0
                drone1_loss = float(drone1_loss) if drone1_loss is not None else 0.0
                drone2_loss = float(drone2_loss) if drone2_loss is not None else 0.0
                drone1_hijack = float(drone1_hijack) if drone1_hijack is not None else 0.0
                drone2_hijack = float(drone2_hijack) if drone2_hijack is not None else 0.0
            
                if drone1_uri and self.hijack_detected.get(drone1_uri, False) and self.hijack_start_time.get(drone1_uri):
                    ongoing = time.time() - self.hijack_start_time[drone1_uri]
                    drone1_hijack += ongoing
            
                if drone2_uri and self.hijack_detected.get(drone2_uri, False) and self.hijack_start_time.get(drone2_uri):
                    ongoing = time.time() - self.hijack_start_time[drone2_uri]
                    drone2_hijack += ongoing
            
                # Write table
                f.write(f"Success Rate         100%         100%         {success_rate:.0f}%\n")
                f.write(f"Time to First       {drone1_time:.1f}s       {drone2_time:.1f}s       {avg_time_to_first:.2f}s\n")
                f.write(f"Max Path Deviation  {drone1_dev:.2f}m       {drone2_dev:.2f}m       {avg_max_deviation:.2f}m\n")
                f.write(f"Telemetry Loss      {drone1_loss:.1f}s       {drone2_loss:.1f}s       {avg_telemetry_loss:.2f}s\n")
                f.write(f"Total Hijack        {drone1_hijack:.1f}s       {drone2_hijack:.1f}s       {avg_hijack_duration:.2f}s\n\n")
            
                f.write("KEY FINDINGS:\n")
                f.write("-"*80 + "\n")
                f.write(f"1. {success_rate:.0f}% Success Rate: {'Both' if success_count == 2 else 'One'} drone(s) hijacked successfully\n")
                f.write(f"2. Rapid Takeover: Average {avg_time_to_first:.2f} seconds to first anomaly\n")
                f.write(f"3. Significant Deviation: Average {avg_max_deviation:.2f}m deviation")
                if avg_max_deviation > 1.0:
                    f.write(" (exceeds 1.0m threshold)\n")
                else:
                    f.write("\n")
                f.write(f"4. Sustained Control: Average {avg_hijack_duration:.2f} seconds of maintained hijack\n\n")
            
                f.write("DETAILED DRONE ANALYSIS:\n")
                f.write("-"*80 + "\n")
                for uri in self.missions.keys():
                    drone_num = list(self.missions.keys()).index(uri) + 1
                
                    # Calculate total hijack duration for this drone
                    total_hijack = self.total_hijack_duration.get(uri, 0)
                    if self.hijack_detected.get(uri, False) and self.hijack_start_time.get(uri):
                        ongoing = time.time() - self.hijack_start_time[uri]
                        total_hijack += ongoing
                
                    # Get values and ensure they're floats
                    max_dev = self.max_path_deviation.get(uri, 0)
                    max_dev = float(max_dev) if max_dev is not None else 0.0
                
                    tele_loss = self.total_telemetry_loss.get(uri, 0)
                    tele_loss = float(tele_loss) if tele_loss is not None else 0.0
                
                    time_first = self.time_to_first_anomaly.get(uri, 0)
                    time_first = float(time_first) if time_first is not None else 0.0
                
                    f.write(f"\nDRONE {drone_num}:\n")
                    f.write(f"  Success: {'YES' if self.hijack_detected.get(uri, False) else 'NO'}\n")
                    f.write(f"  Max Path Deviation: {max_dev:.2f}m")
                    if max_dev > 1.0:
                        f.write(" (>1.0m SUCCESS)\n")
                    else:
                        f.write("\n")
                    f.write(f"  Total Telemetry Loss: {tele_loss:.1f}s")
                    if tele_loss > 3.0:
                        f.write(" (>3s SUCCESS)\n")
                    else:
                        f.write("\n")
                    f.write(f"  Time to First Anomaly: {time_first:.1f}s\n")
                    f.write(f"  Total Hijack Duration: {total_hijack:.1f}s\n")
        
            self.add_message(f"Experiment summary saved to: {summary_file}", "SYSTEM")
            print(f"\n[EXPERIMENT] Summary saved to: {summary_file}")
        
            # Print summary to console
            print("\n" + "="*60)
            print("SWARM HIJACKING PERFORMANCE METRICS")
            print("="*60)
            print("Metric               Drone 1      Drone 2      Average")
            print("-"*60)
            print(f"Success Rate         100%         100%         {success_rate:.0f}%")
            print(f"Time to First       {drone1_time:.1f}s       {drone2_time:.1f}s       {avg_time_to_first:.2f}s")
            print(f"Max Path Deviation  {drone1_dev:.2f}m       {drone2_dev:.2f}m       {avg_max_deviation:.2f}m")
            print(f"Telemetry Loss      {drone1_loss:.1f}s       {drone2_loss:.1f}s       {avg_telemetry_loss:.2f}s")
            print(f"Total Hijack        {drone1_hijack:.1f}s       {drone2_hijack:.1f}s       {avg_hijack_duration:.2f}s")
            print("="*60)
        
        except Exception as e:
            print(f"[ERROR] Failed to generate summary: {e}")
            import traceback
            traceback.print_exc()
    
    def setup_plot_with_messages(self):
        """Setup the main plot with side message panel."""
        self.fig = plt.figure(figsize=(18, 8))
        gs = gridspec.GridSpec(1, 2, width_ratios=[2, 1])
        
        self.ax = plt.subplot(gs[0])
        self.msg_ax = plt.subplot(gs[1])
        self.msg_ax.set_facecolor('#f8f9fa')
        self.msg_ax.set_xlim(0, 1)
        self.msg_ax.set_ylim(0, 1)
        self.msg_ax.axis('off')
        
        self.msg_ax.text(0.5, 0.95, 'HIJACK EXPERIMENT LOG', 
                        fontsize=14, weight='bold', ha='center',
                        bbox=dict(boxstyle="round,pad=0.5", facecolor='lightblue', alpha=0.8))
        
        self.fig.canvas.mpl_connect('key_press_event', self.on_key_press)
        
        plt.tight_layout()
        plt.ion()
        plt.show(block=False)
        plt.pause(0.1)
    
    def on_key_press(self, event):
        """
        Handle keyboard events for scrolling messages.
        
        Args:
            event: Matplotlib key press event
        """
        total_pages = max(1, (len(self.message_history) + self.message_display_count - 1) // self.message_display_count)
        
        if event.key == 'up' or event.key == 'pageup':
            self.current_page = min(self.current_page + 1, total_pages - 1)
            self.update_message_display()
        elif event.key == 'down' or event.key == 'pagedown':
            self.current_page = max(self.current_page - 1, 0)
            self.update_message_display()
        elif event.key == 'home':
            self.current_page = 0
            self.update_message_display()
    
    def add_message(self, message, msg_type="INFO"):
        """
        Add a message to the message history and update display.
        
        Args:
            message: Message text
            msg_type: Type of message (INFO, ANOMALY, RECOVERY, etc.)
        """
        timestamp = datetime.now().strftime('%H:%M:%S')
        formatted_message = f"[{timestamp}] {message}"
        
        if msg_type == "ANOMALY":
            color = 'red'
            prefix = "[HIJACK] "
        elif msg_type == "RECOVERY":
            color = 'green'
            prefix = "[OK] "
        elif msg_type == "CONTROLLER":
            color = 'blue'
            prefix = "[CTRL] "
        elif msg_type == "SYSTEM":
            color = 'purple'
            prefix = "[SYS] "
        elif msg_type == "DATA_RATE":
            color = 'orange'
            prefix = "[DATA] "
        elif msg_type == "SUCCESS":
            color = 'darkgreen'
            prefix = "[SUCCESS] "
        else:
            color = 'black'
            prefix = "[INFO] "
        
        full_message = f"{prefix}{formatted_message}"
        self.message_history.appendleft((full_message, color))
        self.update_message_display()
    
    def update_message_display(self):
        """Update the message panel with current messages."""
        self.msg_ax.clear()
        self.msg_ax.set_facecolor('#f8f9fa')
        self.msg_ax.set_xlim(0, 1)
        self.msg_ax.set_ylim(0, 1)
        self.msg_ax.axis('off')
        
        self.msg_ax.text(0.5, 0.97, 'REAL-TIME HIJACK MONITOR', 
                        fontsize=14, weight='bold', ha='center', color='navy',
                        bbox=dict(boxstyle="round,pad=0.5", facecolor='lightblue', alpha=0.8))
        
        total_pages = max(1, (len(self.message_history) + self.message_display_count - 1) // self.message_display_count)
        
        y_position = 0.90
        line_height = 0.055
        
        start_idx = self.current_page * self.message_display_count
        end_idx = start_idx + self.message_display_count
        
        messages_to_show = list(self.message_history)[start_idx:end_idx]
        
        for i, (message, color) in enumerate(messages_to_show):
            if y_position > 0.15:
                self.msg_ax.add_patch(Rectangle((0.02, y_position - 0.025), 0.96, 0.05,
                                              facecolor='white', alpha=0.7, edgecolor='lightgray'))
                
                self.msg_ax.text(0.05, y_position, message, 
                               fontsize=8, color=color, ha='left', va='top',
                               wrap=True, fontfamily='monospace')
                y_position -= line_height
        
        if total_pages > 1:
            page_info = f"Page {self.current_page + 1} of {total_pages}"
            instructions = "UP/DOWN: Scroll  HOME: Latest messages"
            
            self.msg_ax.text(0.5, 0.10, page_info,
                           fontsize=9, color='blue', ha='center', weight='bold',
                           bbox=dict(boxstyle="round,pad=0.3", facecolor='lightyellow', alpha=0.8))
            self.msg_ax.text(0.5, 0.06, instructions,
                           fontsize=7, color='gray', ha='center', style='italic')
        
        plt.draw()
    
    def check_data_rate_anomaly(self, uri, current_time, has_new_data=True, data_timestamp=None):
        """
        Enhanced data rate monitoring with hijack detection.
        
        Args:
            uri: Drone URI
            current_time: Current timestamp
            has_new_data: Whether new data was received
            data_timestamp: Timestamp of data (optional)
        
        Returns:
            Tuple of (anomaly_detected, time_since_data, anomaly_level)
        """
        if uri not in self.last_data_timestamps:
            self.last_data_timestamps[uri] = current_time
            self.last_actual_data_timestamps[uri] = current_time
            self.data_rate_anomalies[uri] = False
            return False, 0, "NORMAL"
    
        if data_timestamp is not None:
            time_since_actual_data = current_time - data_timestamp
            self.last_actual_data_timestamps[uri] = data_timestamp
        else:
            time_since_actual_data = current_time - self.last_actual_data_timestamps.get(uri, current_time)
    
        if has_new_data:
            self.last_data_timestamps[uri] = current_time
    
        # Check thresholds based on success criteria
        warning_threshold = 2.0
        alarm_threshold = 3.0
        critical_threshold = 5.0
    
        if time_since_actual_data > critical_threshold:
            anomaly_level = "CRITICAL"
            data_rate_anomaly = True
        elif time_since_actual_data > alarm_threshold:
            anomaly_level = "ALARM" 
            data_rate_anomaly = True
        elif time_since_actual_data > warning_threshold:
            anomaly_level = "WARNING"
            data_rate_anomaly = True
        else:
            anomaly_level = "NORMAL"
            data_rate_anomaly = False
    
        return data_rate_anomaly, time_since_actual_data, anomaly_level
    
    def cleanup_previous_logs(self):
        """Delete all previous drone log files for a clean start."""
        self.add_message("Cleaning up previous log files...", "SYSTEM")
        
        log_files = glob.glob("drone_position_*.jsonl")
        deleted_count = 0
        
        for log_file in log_files:
            try:
                os.remove(log_file)
                deleted_count += 1
            except Exception as e:
                self.add_message(f"Could not delete {log_file}: {e}", "SYSTEM")
        
        if deleted_count == 0:
            self.add_message("No previous log files found", "SYSTEM")
        else:
            self.add_message(f"Removed {deleted_count} previous log file(s)", "SYSTEM")
    
    def setup_mission_layout(self):
        """Setup the mission layout using start positions from missions dictionary."""
        self.ax.clear()
        colors = ['green', 'blue', 'red', 'orange', 'purple', 'brown']
        
        for i, (uri, (start_point, delivery_points)) in enumerate(self.missions.items()):
            color = colors[i % len(colors)]
            self.drone_colors[uri] = color
            self.controller_history[uri] = []
            self.anomaly_status[uri] = False
            drone_name = f"Drone {i+1}"
            
            self.add_message(f"{drone_name} assigned color: {color.upper()}", "SYSTEM")
            
            start_x, start_y = start_point
            self.ax.plot(start_x, start_y, 'o', markersize=20, color=color,
                        label=f'{drone_name} Start', markeredgecolor='black', markeredgewidth=3)
            self.ax.text(start_x, start_y + 0.2, 'START',
                        fontsize=12, color=color, ha='center', weight='bold',
                        bbox=dict(boxstyle="round,pad=0.3", facecolor='white', alpha=0.8))
            
            for j, (dx, dy) in enumerate(delivery_points):
                self.ax.plot(dx, dy, 's', markersize=15, color=color,
                           markerfacecolor='none', markeredgewidth=3, markeredgecolor=color)
                self.ax.text(dx, dy + 0.2, f'Delivery {j+1}',
                           fontsize=10, color=color, ha='center', weight='bold',
                           bbox=dict(boxstyle="round,pad=0.3", facecolor='white', alpha=0.8))
            
            path = self.generate_grid_path(start_point, delivery_points)
            if path:
                path_x = [point[0] for point in path]
                path_y = [point[1] for point in path]
                self.ax.plot(path_x, path_y, '--', color=color, alpha=0.5, linewidth=2,
                           label=f'{drone_name} Expected Path')
                self.drone_paths[uri] = path
        
        self.ax.set_xlim(-2.0, 2.0)
        self.ax.set_ylim(-2.0, 3.0)
        self.ax.set_xlabel('X Coordinate (meters)', fontsize=12)
        self.ax.set_ylabel('Y Coordinate (meters)', fontsize=12)
        self.ax.set_title('Real-time Drone Hijack Monitoring\nBoth drones monitored for hijack symptoms', 
                         fontsize=14, weight='bold')
        self.ax.grid(True, alpha=0.3)
        self.ax.legend(loc='upper right')
        
        for uri in self.missions.keys():
            self.drone_positions[uri] = []
            filename = self.find_drone_log_file(uri)
            if filename:
                self.drone_files[uri] = filename
                self.add_message(f"Tracking {uri}", "SYSTEM")
            else:
                filename = f"drone_position_{uri.replace('://', '_').replace('/', '_')}.jsonl"
                self.drone_files[uri] = filename
                self.add_message(f"Waiting for log file: {filename}", "SYSTEM")
        
        plt.draw()
        plt.pause(0.1)
    
    def generate_grid_path(self, start, waypoints):
        """
        Generate the expected grid path using start position from missions.
        
        Args:
            start: Tuple of (x, y) start coordinates
            waypoints: List of (x, y) delivery points
        
        Returns:
            List of (x, y, z, yaw) path points
        """
        path = []
        height = 0.6
        streetX = start[0]
    
        # Add start point as first path point
        start_x, start_y = start
        path.append((start_x, start_y, height, 0))
    
        for target in waypoints:
            yaw = 0
            path.append((streetX, target[1], height, yaw))
        
            if streetX != target[0]:
                path.append((target[0], target[1], height, yaw))
                path.append((streetX, target[1], height, yaw))
        return path
    
    def find_drone_log_file(self, uri):
        """
        Find the log file for a drone URI.
        
        Args:
            uri: Drone URI
        
        Returns:
            Filename if found, None otherwise
        """
        parts = uri.split('/')
        drone_id = parts[-1]
    
        pattern = f"drone_position_*{drone_id}*.jsonl"
        files = glob.glob(pattern)
    
        if files:
            return files[0]
    
        return None
    
    def distance_to_line_segment(self, px, py, p1, p2):
        """
        Calculate minimum distance from point to line segment.
        
        Args:
            px, py: Point coordinates
            p1, p2: Line segment endpoints
        
        Returns:
            Minimum distance
        """
        x1, y1 = p1
        x2, y2 = p2
    
        dx = x2 - x1
        dy = y2 - y1
    
        # If segment is a point
        if dx == 0 and dy == 0:
            return np.sqrt((px - x1)**2 + (py - y1)**2)
    
        # Project point onto line
        t = ((px - x1) * dx + (py - y1) * dy) / (dx * dx + dy * dy)
    
        # Clamp t to segment range [0, 1]
        if t < 0:
            # Closest to p1
            return np.sqrt((px - x1)**2 + (py - y1)**2)
        elif t > 1:
            # Closest to p2
            return np.sqrt((px - x2)**2 + (py - y2)**2)
        else:
            # Closest point is on the segment
            proj_x = x1 + t * dx
            proj_y = y1 + t * dy
            return np.sqrt((px - proj_x)**2 + (py - proj_y)**2)

    def check_if_off_course(self, uri, x, y):
        """
        Check if drone is far from its expected path between waypoints.
        
        Args:
            uri: Drone URI
            x, y: Current position
        
        Returns:
            Tuple of (off_course, distance_from_path)
        """
        if uri not in self.drone_paths:
            return False, 0

        expected_path = self.drone_paths[uri]

        if not expected_path:
            return False, 0

        # Use time since first data for this drone instead of global experiment time
        if not hasattr(self, 'first_data_time') or uri not in self.first_data_time:
            # Fall back to global experiment time if first data time not recorded
            experiment_time = time.time() - self.experiment_start_time
        else:
            experiment_time = time.time() - self.first_data_time[uri]
            if experiment_time < 0:
                experiment_time = 0
    
        # Initialize takeoff tolerance tracking - 25 seconds from first data
        if not hasattr(self, 'takeoff_end_time_experiment'):
            self.takeoff_end_time_experiment = {}
    
        if uri not in self.takeoff_end_time_experiment:
            # Set takeoff tolerance to 25 seconds into the mission (from first data)
            self.takeoff_end_time_experiment[uri] = 25.0
            drone_num = list(self.missions.keys()).index(uri) + 1
            self.add_message(f"Drone {drone_num} - takeoff tolerance until {self.takeoff_end_time_experiment[uri]:.1f}s after first data", "SYSTEM")
    
        # Check if we're still in takeoff tolerance period
        is_takeoff_phase = experiment_time < self.takeoff_end_time_experiment[uri]

        if not hasattr(self, 'drone_progress'):
            self.drone_progress = {}

        if uri not in self.drone_progress:
            self.drone_progress[uri] = {
                'current_target_index': 1,
                'last_position': None,
                'last_update_time': experiment_time,
                'last_passed_index': 0,
                'delivery_phase_until': 0
            }

        progress = self.drone_progress[uri]
        current_target_index = progress['current_target_index']

        if current_target_index >= len(expected_path):
            return False, 0

        target_point = expected_path[current_target_index]
        target_x, target_y = target_point[0], target_point[1]

        previous_index = progress['last_passed_index']
        prev_point = expected_path[previous_index]
        prev_x, prev_y = prev_point[0], prev_point[1]

        distance_to_path_segment = self.distance_to_line_segment(x, y, (prev_x, prev_y), (target_x, target_y))
        distance_to_target = np.sqrt((x - target_x)**2 + (y - target_y)**2)

        reached_target = distance_to_target < 0.3

        if reached_target:
            progress['last_passed_index'] = current_target_index
            progress['current_target_index'] += 1
            progress['delivery_phase_until'] = experiment_time + 20.0
            drone_num = list(self.missions.keys()).index(uri) + 1
            self.add_message(f"Drone {drone_num} reached waypoint {current_target_index} - delivery phase for 20s", "CONTROLLER")
            return False, 0

        # Check if we're in delivery phase (descent/ascent)
        is_delivery_phase = experiment_time < progress.get('delivery_phase_until', 0)

        # During takeoff phase, never flag
        if is_takeoff_phase:
            off_course = False
            if distance_to_path_segment > self.max_path_deviation.get(uri, 0):
                self.max_path_deviation[uri] = distance_to_path_segment
        # During delivery phase, use higher threshold (allow descent/ascent deviations)
        elif is_delivery_phase:
            # Higher threshold during delivery (0.5m instead of 0.3m)
            off_course = distance_to_path_segment > 0.5
        else:
            # Normal flight - standard threshold
            off_course = distance_to_path_segment > 0.3

        progress['last_position'] = (x, y)
        progress['last_update_time'] = experiment_time

        if off_course and not is_takeoff_phase:
            drone_num = list(self.missions.keys()).index(uri) + 1
            threshold_str = "0.5m" if is_delivery_phase else "0.3m"
            self.add_message(f"HIJACK SUCCESS: Drone {drone_num} deviated {distance_to_path_segment:.2f}m from expected path (> {threshold_str})", "SUCCESS")

        return off_course, distance_to_path_segment

    def read_latest_positions(self):
        """
        Read the latest positions from all drone log files.
        
        Returns:
            Dictionary mapping URIs to latest position data
        """
        new_positions = {}
        current_time = time.time()
    
        # Track when we first see data for each drone (for takeoff tolerance)
        if not hasattr(self, 'first_data_time'):
            self.first_data_time = {}
    
        for uri, filename in self.drone_files.items():
            if os.path.exists(filename):
                try:
                    found_new_data = False
                    latest_data_timestamp = None
            
                    with open(filename, 'r') as f:
                        lines = f.readlines()
            
                    for line in reversed(lines):
                        line = line.strip()
                        if line and not line.startswith('#') and 'event' not in line:
                            try:
                                data = json.loads(line)
                                if 'x' in data and 'y' in data and 'z' in data:
                                    found_new_data = True
                                    data_timestamp = data.get('timestamp', current_time)
                                    latest_data_timestamp = data_timestamp
                            
                                    # Record when we first see data for this drone
                                    if uri not in self.first_data_time:
                                        self.first_data_time[uri] = data_timestamp
                                        self.add_message(f"Drone {list(self.missions.keys()).index(uri) + 1} first data recorded", "SYSTEM")
                            
                                    data_rate_anomaly, time_since_data, anomaly_level = self.check_data_rate_anomaly(
                                        uri, current_time, has_new_data=True, data_timestamp=data_timestamp)
                            
                                    new_positions[uri] = {
                                        'x': data['x'],
                                        'y': data['y'], 
                                        'z': data['z'],
                                        'timestamp': data_timestamp,
                                        'controller': data.get('controller', 'unknown'),
                                        'datetime': data.get('datetime', ''),
                                        'data_rate_anomaly': data_rate_anomaly,
                                        'time_since_data': time_since_data,
                                        'anomaly_level': anomaly_level,
                                        'data_age': current_time - data_timestamp,
                                        'is_off_course': False,
                                        'distance_from_path': 0,
                                        'current_speed': 0,
                                        'speed_violation': False
                                    }
                                    break
                            except json.JSONDecodeError:
                                continue
            
                    if not found_new_data:
                        data_rate_anomaly, time_since_data, anomaly_level = self.check_data_rate_anomaly(
                            uri, current_time, has_new_data=False)
                
                        if uri in self.drone_positions and self.drone_positions[uri]:
                            last_pos = self.drone_positions[uri][-1]
                            new_positions[uri] = {
                                'x': last_pos[0], 'y': last_pos[1], 'z': 0,
                                'timestamp': current_time,
                                'controller': 'unknown',
                                'data_rate_anomaly': data_rate_anomaly,
                                'time_since_data': time_since_data,
                                'anomaly_level': anomaly_level,
                                'stale_data': True,
                                'data_age': time_since_data
                            }
                        else:
                            drone_num = list(self.missions.keys()).index(uri) + 1
                            message = f"NO DATA: Drone {drone_num} - no position data"
                            self.add_message(message, "DATA_RATE")
        
                except Exception as e:
                    error_msg = f"Error reading {filename}: {e}"
                    self.add_message(error_msg, "SYSTEM")
    
        return new_positions
    
    def update_controller_history(self, uri, controller, is_anomaly=False, is_data_anomaly=False):
        """
        Update controller history and detect changes.
        
        Args:
            uri: Drone URI
            controller: Controller name
            is_anomaly: Whether path anomaly is present
            is_data_anomaly: Whether data anomaly is present
        """
        if uri not in self.controller_history:
            self.controller_history[uri] = []
        
        current_time = time.time()
        current_anomaly = is_anomaly or is_data_anomaly
        
        if current_anomaly != self.anomaly_status.get(uri, False):
            if current_anomaly:
                self.anomaly_start_time[uri] = current_time
                drone_num = list(self.missions.keys()).index(uri) + 1
                if is_data_anomaly:
                    self.add_message(f"DATA ANOMALY: Drone {drone_num} comms lost", "DATA_RATE")
                else:
                    self.add_message(f"PATH ANOMALY: Drone {drone_num} off-course", "ANOMALY")
            else:
                anomaly_duration = current_time - self.anomaly_start_time.get(uri, current_time)
                drone_num = list(self.missions.keys()).index(uri) + 1
                self.add_message(f"RECOVERED: Drone {drone_num} back normal {anomaly_duration:.1f}s", "RECOVERY")
            
            self.anomaly_status[uri] = current_anomaly
        
        if (not self.controller_history[uri] or 
            self.controller_history[uri][-1]['controller'] != controller or
            self.controller_history[uri][-1]['anomaly'] != current_anomaly or
            current_time - self.controller_history[uri][-1]['timestamp'] > 5):
            
            self.controller_history[uri].append({
                'controller': controller,
                'anomaly': current_anomaly,
                'path_anomaly': is_anomaly,
                'data_anomaly': is_data_anomaly,
                'timestamp': current_time,
                'time_str': datetime.now().strftime('%H:%M:%S')
            })
            
            if len(self.controller_history[uri]) > 10:
                self.controller_history[uri] = self.controller_history[uri][-10:]
            
            drone_num = list(self.missions.keys()).index(uri) + 1
            status_parts = []
            if is_anomaly:
                status_parts.append("PATH_ISSUE")
            if is_data_anomaly:
                status_parts.append("DATA_ISSUE")
            status = " | ".join(status_parts) if status_parts else "NORMAL"
            self.add_message(f"Drone {drone_num}: {controller.upper()} | {status}", "CONTROLLER")
    
    def is_drone_landed(self, uri, pos_data):
        """
        Check if drone has landed (mission complete and low altitude).
        
        Args:
            uri: Drone URI
            pos_data: Current position data
        
        Returns:
            True if drone is landed/dormant, False otherwise
        """
        # Get mission progress
        progress = self.get_mission_progress(uri)
        mission_complete = progress.get('progress', 0) >= 1.0
    
        # Check altitude - landed if z < 0.1m (close to ground)
        z_height = pos_data.get('z', 1.0)
        is_landed = z_height < 0.1
    
        # Also check if data is very old (5+ seconds without update)
        data_age = pos_data.get('data_age', 0)
        is_inactive = data_age > 5.0
    
        # Also check if drone has been stationary for a while
        if uri in self.drone_positions and len(self.drone_positions[uri]) > 5:
            recent_positions = self.drone_positions[uri][-5:]
            if len(recent_positions) >= 3:
                x_positions = [p[0] for p in recent_positions]
                y_positions = [p[1] for p in recent_positions]
                x_range = max(x_positions) - min(x_positions)
                y_range = max(y_positions) - min(y_positions)
                is_stationary = x_range < 0.05 and y_range < 0.05
            else:
                is_stationary = False
        else:
            is_stationary = False
    
        # Drone is dormant if mission complete AND landed, OR stationary and inactive
        return (mission_complete and is_landed) or (is_stationary and is_inactive)
    
    def update_plot(self):
        """
        Update the plot with latest positions from log files.
        
        Returns:
            Tuple of (active_count, controllers, path_anomalies, data_anomalies, hijack_count)
        """
        # Remove old drone markers
        for artist in self.ax.collections[:]:
            if hasattr(artist, '_drone_marker'):
                artist.remove()
        
        latest_positions = self.read_latest_positions()
        
        active_drones = 0
        current_controllers = {}
        anomaly_drones = 0
        data_anomaly_drones = 0
        hijack_drones = 0
        
        for uri, pos_data in latest_positions.items():
            if pos_data:
                active_drones += 1
                x, y, z = pos_data['x'], pos_data['y'], pos_data['z']
                controller = pos_data.get('controller', 'unknown')
                data_rate_anomaly = pos_data.get('data_rate_anomaly', False)
                data_age = pos_data.get('data_age', 0)
                current_controllers[uri] = controller
                
                # Check if drone is off-course
                is_off_course, distance_from_path = self.check_if_off_course(uri, x, y)
                
                # Update pos_data so alerts can access these values
                pos_data['is_off_course'] = is_off_course
                pos_data['distance_from_path'] = distance_from_path
                
                # Check if drone is dormant for THIS drone
                is_dormant = self.is_drone_landed(uri, pos_data)
                
                # Detect hijack based on success criteria (only if not dormant)
                hijack_detected = False
                anomaly_type = "NONE"
                current_time = time.time()
                
                if not is_dormant:
                    # Success criteria
                    if data_age > 3.0:
                        hijack_detected = True
                        anomaly_type = "TELEMETRY_LOSS"
                    elif distance_from_path > 0.3:
                        hijack_detected = True
                        anomaly_type = "PATH_DEVIATION"
                    elif data_rate_anomaly and pos_data.get('anomaly_level') in ["ALARM", "CRITICAL"]:
                        hijack_detected = True
                        anomaly_type = "HIJACK_DETECTED"
                
                # Update hijack metrics and record results
                if hijack_detected:
                    self.update_hijack_metrics(uri, anomaly_type, current_time, 
                                              distance_from_path, data_age)
                    
                    self.record_hijack_result(uri, pos_data, distance_from_path, 
                                             data_age, hijack_detected, anomaly_type)
                    
                    hijack_drones += 1
                    if not self.hijack_detected[uri]:
                        self.hijack_detected[uri] = True
                
                self.update_controller_history(uri, controller, is_off_course, data_rate_anomaly)
                
                if is_off_course:
                    anomaly_drones += 1
                if data_rate_anomaly:
                    data_anomaly_drones += 1
                
                color = self.drone_colors.get(uri, 'black')
                anomaly_level = pos_data.get('anomaly_level', 'NORMAL')
                stale_data = pos_data.get('stale_data', False)

                # Determine marker style based on hijack status
                if hijack_detected:
                    marker = '*'
                    marker_color = 'darkred'
                    marker_size = 120
                elif stale_data:
                    marker = 'o'
                    marker_color = 'gray'
                    marker_size = 40
                elif is_off_course and data_rate_anomaly:
                    if anomaly_level == "CRITICAL":
                        marker = '^'
                        marker_color = 'darkred'
                        marker_size = 140
                    elif anomaly_level == "ALARM":
                        marker = '^' 
                        marker_color = 'red'
                        marker_size = 120
                    else:
                        marker = '^'
                        marker_color = 'orange'
                        marker_size = 100
                elif is_off_course:
                    marker = 'X'
                    marker_color = 'red'
                    marker_size = 100
                elif data_rate_anomaly:
                    if anomaly_level == "CRITICAL":
                        marker = 'D'
                        marker_color = 'darkred' 
                        marker_size = 120
                    elif anomaly_level == "ALARM":
                        marker = 'D'
                        marker_color = 'red'
                        marker_size = 100
                    else:
                        marker = 'D'
                        marker_color = 'orange'
                        marker_size = 80
                else:
                    marker = 'o'
                    marker_color = color
                    marker_size = 50
                
                self.ax.scatter(x, y, c=marker_color, s=marker_size, marker=marker,
                              edgecolors='white', linewidth=1.5, alpha=0.9,
                              label='_nolegend_')
                
                if uri not in self.drone_positions:
                    self.drone_positions[uri] = []
                self.drone_positions[uri].append((x, y))
                
                if len(self.drone_positions[uri]) > 100:
                    self.drone_positions[uri] = self.drone_positions[uri][-100:]
        
        status_text = f"Active: {active_drones} | Path Issues: {anomaly_drones} | Data Issues: {data_anomaly_drones} | Hijacked: {hijack_drones}"
        if hijack_drones > 0:
            title_color = 'darkgreen'
        elif anomaly_drones > 0 or data_anomaly_drones > 0:
            title_color = 'red'
        else:
            title_color = 'black'
        self.ax.set_title(f'Real-time Drone Hijack Monitoring\n{status_text}', 
                         fontsize=14, weight='bold', color=title_color)
        
        if hasattr(self, 'color_legend'):
            self.color_legend.remove()
            
        legend_text = "HIJACK MONITORING (BOTH DRONES):\n"
        for uri, color in self.drone_colors.items():
            drone_num = list(self.missions.keys()).index(uri) + 1
            hijack_status = "HIJACKED" if self.hijack_detected.get(uri, False) else "OK"
            legend_text += f"• {color.upper()} = Drone {drone_num} [{hijack_status}]\n"
        
        legend_text += "\nSUCCESS INDICATORS:\n"
        legend_text += "* GREEN STAR = Hijack success detected\n"
        legend_text += "• >0.3m deviation OR >3s data loss\n"
        
        self.color_legend = self.ax.text(0.02, 0.98, legend_text,
            transform=self.ax.transAxes, fontsize=8, verticalalignment='top',
            bbox=dict(boxstyle="round,pad=0.5", facecolor='lightblue', alpha=0.8))
        
        plt.draw()
        plt.pause(0.01)
        
        return active_drones, current_controllers, anomaly_drones, data_anomaly_drones, hijack_drones
    
    def complete_experiment(self):
        """Complete the experiment and generate final report."""
        print("\n" + "="*60)
        print("COMPLETING EXPERIMENT AND GENERATING REPORT")
        print("="*60)
    
        current_time = time.time()
    
        # Finalize metrics
        for uri in self.missions.keys():
            # Add any ongoing hijack time to total
            if self.hijack_detected.get(uri, False) and self.hijack_start_time.get(uri):
                ongoing_duration = current_time - self.hijack_start_time[uri]
                self.total_hijack_duration[uri] = self.total_hijack_duration.get(uri, 0) + ongoing_duration
                self.hijack_detected[uri] = False
            
            # Calculate final telemetry loss if still in data anomaly
            if self.current_data_anomaly_start.get(uri):
                self.total_telemetry_loss[uri] = current_time - self.current_data_anomaly_start[uri]
    
        # Generate summary
        self.generate_experiment_summary()
    
        # Add final messages
        self.add_message("="*50, "SYSTEM")
        self.add_message("EXPERIMENT COMPLETE", "SYSTEM")
        self.add_message(f"Total duration: {current_time - self.experiment_start_time:.1f}s", "SYSTEM")
        self.add_message(f"Report saved to: {self.results_file.replace('.csv', '_summary.txt')}", "SYSTEM")
        self.add_message("="*50, "SYSTEM")

    def run_realtime_plot(self, update_interval=0.5, duration=None):
        """
        Run the real-time plotter with experiment duration.
        
        Args:
            update_interval: Seconds between plot updates
            duration: Total experiment duration in seconds (None for indefinite)
        """
        self.add_message(f"Starting hijack experiment: {self.experiment_name}", "SYSTEM")
        if duration:
            self.add_message(f"Experiment will run for {duration} seconds", "SYSTEM")
        else:
            self.add_message("Experiment will run until Ctrl+C is pressed", "SYSTEM")
        self.add_message("Success criteria: Telemetry loss >3s OR Path deviation >0.3m", "SYSTEM")
        self.add_message("Monitoring BOTH drones for hijack symptoms", "SYSTEM")
    
        last_update = 0
        start_time = time.time()
    
        try:
            while True:
                if duration and (time.time() - start_time) > duration:
                    self.add_message(f"Experiment completed after {duration} seconds", "SYSTEM")
                    print(f"\n[EXPERIMENT] Completed after {duration} seconds")
                    break
                    
                current_time = time.time()
                if current_time - last_update >= update_interval:
                    active_count, controllers, path_anomalies, data_anomalies, hijack_count = self.update_plot()
                    last_update = current_time
                
                    if int(current_time) % 15 == 0:
                        if hijack_count > 0:
                            self.add_message(f"HIJACK STATUS: {hijack_count}/{len(self.missions)} drones hijacked", "SUCCESS")
                        else:
                            self.add_message(f"Status: {active_count} active, {path_anomalies} path issues, {data_anomalies} data issues", "INFO")
            
                time.sleep(0.1)
            
        except KeyboardInterrupt:
            print("\n\n[EXPERIMENT] Ctrl+C detected!")
            self.add_message("Experiment interrupted by user", "SYSTEM")
    
        except Exception as e:
            print(f"\n[EXPERIMENT] Error: {e}")
            self.add_message(f"Plotter error: {e}", "SYSTEM")
            import traceback
            traceback.print_exc()
    
        finally:
            # Always complete experiment and generate report
            self.complete_experiment()
        
            # Keep plot open
            plt.ioff()
            plt.show(block=True)


# Mission definitions: URI -> (start_position, waypoints)
missions = {
    'radio://0/80/2M/E7E7E7E7E9': (
        (0.23, -2.1),
        [(0.85, -1.24), (0.85, -0.78), (0.85, 0.85)]  
    ),
    'radio://0/80/2M/E7E7E7E7E8': (
        (-0.29, -2.1), 
        [(-1.04, -0.93), (-1.04, 1.09)] 
    )
}


if __name__ == '__main__':
    # Check if log files exist
    print("Checking for log files...")
    log_files = glob.glob("drone_position_*.jsonl")
    
    if log_files:
        print(f"Found {len(log_files)} log files:")
        for f in log_files:
            print(f"  - {f}")
    else:
        print("WARNING: No log files found!")
        print("Expected files: drone_position_*.jsonl")
        print("Make sure drone simulation is running first.")
    
    # Create plotter with experiment name
    plotter = DroneMissionPlotter(missions, experiment_name="swarm_hijack_experiment")
    
    print("\n" + "="*60)
    print("DRONE HIJACKING SUCCESS DETECTOR")
    print("="*60)
    print("Success Criteria:")
    print("  1. Telemetry loss > 3 seconds")
    print("  2. Path deviation > 0.3 meters")
    print("  3. Manual hijack detection flag")
    print("")
    print("BOTH drones are monitored for these symptoms")
    print("Results will be saved for statistical analysis")
    print("="*60)
    print("\nWaiting for drone position data from log files...")
    print("Press Ctrl+C at any time to generate report and exit")
    time.sleep(2)
    
    # Run indefinitely until Ctrl+C
    plotter.run_realtime_plot(update_interval=0.5, duration=None)
